export const authContent = {
  en: {
    label: "Authentication entry",
    loginTitle: "Welcome back to ViseCraft.",
    signupTitle: "Create your ViseCraft workspace.",
    explanation:
      "Account login is separate from GitHub repository connection. Signing in with GitHub does not grant ViseCraft repository access until you connect a project source inside the app.",
    returnHome: "Return to landing page",
    signIn: "Sign in",
    requestAccess: "Request early access",
    loginIntro: "Use email and password, or GitHub login when Supabase OAuth is configured.",
    signupIntro: "Create a starter workspace for the private alpha flow.",
    github: "Sign in with GitHub",
    orEmail: "or email",
    name: "Name",
    email: "Email",
    password: "Password",
    namePlaceholder: "Ada Founder",
    emailPlaceholder: "founder@example.com",
    passwordPlaceholder: "At least 8 characters",
    terms: "I agree to the Terms and understand ViseCraft is in early access.",
    createAccount: "Create account",
    alreadyHaveAccount: "Already have an account?",
    forgotPassword: "Forgot password?",
    previewNotice:
      "Preview auth is active because Supabase env vars are not configured. It uses an HTTP-only cookie for local MVP verification. Production deployments should set Supabase Auth env vars and use real provider sessions.",
    errors: {
      invalidEmail: "Enter a valid email address.",
      shortPassword: "Password must be at least 8 characters.",
      incompleteSignup: "Add your name and accept the terms to continue.",
      authNotConfigured: "Authentication is not configured in this environment.",
      authFailed: "Authentication failed.",
      githubNeedsSupabase:
        "GitHub login requires Supabase Auth to be configured. Use preview email login locally.",
      githubFailed: "GitHub login failed.",
      resetNeedsEmail: "Enter your email first, then request a reset link.",
      resetPreview: "Password reset is available once Supabase Auth is configured.",
      resetSent: "Password reset email sent.",
      resetFailed: "Password reset failed.",
    },
  },
  zh: {
    label: "认证入口",
    loginTitle: "欢迎回到 ViseCraft。",
    signupTitle: "创建你的 ViseCraft 工作区。",
    explanation:
      "账号登录与 GitHub 仓库连接是两件事。使用 GitHub 登录只代表身份认证，不会自动授权 ViseCraft 访问你的仓库；仓库连接会在应用内单独完成。",
    returnHome: "返回首页",
    signIn: "登录",
    requestAccess: "申请早期访问",
    loginIntro: "使用邮箱和密码登录；配置 Supabase OAuth 后可使用 GitHub 登录。",
    signupIntro: "为私有 Alpha 流程创建一个基础工作区。",
    github: "使用 GitHub 登录",
    orEmail: "或使用邮箱",
    name: "姓名",
    email: "邮箱",
    password: "密码",
    namePlaceholder: "创始人姓名",
    emailPlaceholder: "founder@example.com",
    passwordPlaceholder: "至少 8 个字符",
    terms: "我同意条款，并理解 ViseCraft 当前处于早期访问阶段。",
    createAccount: "创建账号",
    alreadyHaveAccount: "已有账号？",
    forgotPassword: "忘记密码？",
    previewNotice:
      "当前启用 preview auth，因为尚未配置 Supabase 环境变量。它使用 HTTP-only cookie 进行本地 MVP 验证。生产部署应配置 Supabase Auth 环境变量并使用真实会话。",
    errors: {
      invalidEmail: "请输入有效邮箱地址。",
      shortPassword: "密码至少需要 8 个字符。",
      incompleteSignup: "请填写姓名并同意条款。",
      authNotConfigured: "当前环境尚未配置认证。",
      authFailed: "认证失败。",
      githubNeedsSupabase: "GitHub 登录需要先配置 Supabase Auth。本地请使用 preview 邮箱登录。",
      githubFailed: "GitHub 登录失败。",
      resetNeedsEmail: "请先输入邮箱，再请求重置链接。",
      resetPreview: "配置 Supabase Auth 后可使用密码重置。",
      resetSent: "密码重置邮件已发送。",
      resetFailed: "密码重置失败。",
    },
  },
};
